Refactored a lot of the form filler + the success page
Ches-ctrl/Cheddar pull request #123
Opened 2024-04-10 16:35 UTC by obreil54

2024-04-10 18:41 UTC, Ches-ctrl commented on app/controllers/job_applications_controller.rb
Can you keep this as perform_later - this does the same as perform_now but keeps the queue order the same

2024-04-10 18:48 UTC, Ches-ctrl requested changes

2024-04-10 18:48 UTC, Ches-ctrl commented on app/controllers/job_applications_controller.rb
Thanks for moving everything to the controller - can be conscious of this in other places across the app

2024-04-10 18:48 UTC, Ches-ctrl commented on app/jobs/apply_job.rb
Where do we call cleanup sessions?

2024-04-10 18:48 UTC, Ches-ctrl commented on app/services/form_filler.rb
- why do we now initialise the session here? 
- Can we make sure we're not initialising twice? 
- Also what does session.visit do relative to find_apply_button?
- Why screenshot before adding the CV/CL?

2024-04-10 18:48 UTC, Ches-ctrl commented on app/controllers/job_applications_controller.rb
Does having a session mean we can run with more than 1 concurrency?

2024-04-10 18:48 UTC, Ches-ctrl commented on app/services/form_filler.rb
Are there any other implications of session rather than page being the thing we attach everything to?

2024-04-10 18:48 UTC, Ches-ctrl commented on app/views/job_applications/show.html.erb
Nice cleanup

2024-04-11 09:55 UTC, obreil54 commented on app/controllers/job_applications_controller.rb
**This is my fault will fix was just trying things**

2024-04-11 09:56 UTC, obreil54 commented on app/controllers/job_applications_controller.rb
YEs potentially this will ensure that theres no confusion within capybara

2024-04-11 09:56 UTC, obreil54 commented on app/jobs/apply_job.rb
This can be deleted was just testing things

2024-04-11 10:03 UTC, obreil54 commented on app/services/form_filler.rb
- Capybara was always initialised here just specifically doing sessions now to potentially allow for concurrency but even if not will just make things a little more robust/less prone to errors and crashes
- It's not
- Visit goes to the job posting url and then clicks apply button. Including session now within all of the methods ensure that they are targeting a particular session(job application)
- It's not what you're seeing after the screenshot is the temporary files being deleted

2024-04-11 10:03 UTC, obreil54 commented on app/services/form_filler.rb
From my testing so far everything works the same

2024-04-15 05:34 UTC, Ches-ctrl commented on app/controllers/job_applications_controller.rb
Can you make this minor update then I'll approve?

2024-04-15 11:37 UTC, Ches-ctrl approved these changes
Super nice changes, thanks for this. Hoping we can get more than one job working soon!

2024-04-15 11:37 UTC, merged