08/05/24 category sidebar fix
Ches-ctrl/Cheddar pull request #154
Opened 2024-05-08 22:19 UTC by daniel-sussman

2024-05-09 05:22 UTC, Ches-ctrl requested changes
One minor change on html_safe and some clarifications we can go through later. THIS IS AWESOME!

2024-05-09 05:22 UTC, Ches-ctrl commented on app/models/concerns/ats/greenhouse/application_fields.rb
I'm wondering why we still get location_click when scraping the form fields. One to perhaps discuss with Ilya as well - ideally we have a perfect scrape.

2024-05-09 05:22 UTC, Ches-ctrl commented on app/models/concerns/ats/greenhouse/application_fields.rb
Also nice that we're pulling directly from the data_url

2024-05-09 05:22 UTC, Ches-ctrl commented on app/models/concerns/ats/recruitee/application_fields.rb
Can we go through this later as to how it works

2024-05-09 05:22 UTC, Ches-ctrl commented on app/models/job.rb
What are the deletes here doing?

2024-05-09 05:22 UTC, Ches-ctrl commented on app/controllers/job_applications_controller.rb
I see you merged in my other PR - how did you do that? And does that mean I can now delete that branch?

2024-05-09 05:22 UTC, Ches-ctrl commented on app/services/category_sidebar.rb
Very interested in how you managed this fix

2024-05-09 05:22 UTC, Ches-ctrl commented on app/services/form_filler.rb
Helpful comment thanks

2024-05-09 05:22 UTC, Ches-ctrl commented on app/services/form_filler.rb
Like the idea of caching in the future

2024-05-09 05:22 UTC, Ches-ctrl commented on app/views/job_applications/_job_application_form.html.erb
In general my understanding is to limit the use of html_safe given its dangerous - think we can remove this here as well

2024-05-09 05:22 UTC, Ches-ctrl commented on app/views/job_applications/_job_application_form.html.erb
How come we now have resume or resume/cv?

2024-05-09 08:44 UTC, daniel-sussman commented on app/controllers/job_applications_controller.rb
Manually! But yes, you can delete that branch now.

2024-05-09 08:45 UTC, daniel-sussman commented on app/models/concerns/ats/greenhouse/application_fields.rb
Think this is necessary for Capybara to operate the form correctly, but yes Ilya knows more about it.

2024-05-09 08:47 UTC, daniel-sussman commented on app/views/job_applications/_job_application_form.html.erb
Thanks for flagging this, I'll correct it.

2024-05-09 08:51 UTC, daniel-sussman commented on app/views/job_applications/_job_application_form.html.erb
Yes, it's potentially dangerous -- but the field_label is data from the ATS, not from users, so unlikely to be malicious. html_safe is necessary in order to display the label with its original html tags. Otherwise you just get a plaintext string full of tags. I think we can use #sanitize as well to avoid risk, but not sure quite what that method does.

2024-05-09 08:54 UTC, daniel-sussman commented on app/models/job.rb
First delete removes :company from the param filters, since it's no longer possible to filter by company.
Second delete because there's a built-in Ruby method (#except) that does the same thing as previously.

2024-05-09 13:42 UTC, daniel-sussman commented
Fixed the 'resume/cv' ambiguity. I added #sanitize before #html_safe in the application_form partial, which I think is the best solution unless we prefer to eliminate styling of application questions.

In terms of _when_ to sanitize the HTML string, would it be better to do that data is collected from the API? My thinking is that there are multiple APIs and therefore multiple sources we'd need to ensure are sanitized, which seems dodgier (and less DRY) than sanitizing in the view.

2024-05-11 08:05 UTC, Ches-ctrl approved these changes
Nice!

2024-05-11 08:06 UTC, merged