Added some simple validations for the application form as well as a t…
Ches-ctrl/Cheddar pull request #155
Opened 2024-05-09 14:10 UTC by obreil54

…emporary solution for failed applications

2024-05-10 15:31 UTC, Ches-ctrl requested changes

2024-05-10 15:31 UTC, Ches-ctrl commented on app/jobs/apply_job.rb
Can you make the status a ternary operator with result[:success] so this is DRY

2024-05-23 12:32 UTC, obreil54 commented on app/jobs/apply_job.rb
Done!

2024-05-24 06:35 UTC, Ches-ctrl requested changes
Pending testing of functionality by Ilya

2024-05-24 10:49 UTC, Ches-ctrl approved these changes
Issues with:
- Spinners
- Not closing the session

To fix on Ilya's return, approving for now

2024-05-24 10:49 UTC, merged