10/06/24 testing
Ches-ctrl/Cheddar pull request #187
Opened 2024-06-11 13:34 UTC by daniel-sussman

Modified CategorySidebar so that it counts jobs in each category according to the filters applied to *other* categories only. This makes it possible to see select more than one filter in the same category. Otherwise they all disappear once a filter is selected. For example, there are 5 jobs in London and 4 jobs in Reading that were posted in the past 3 days (I've selected 'Last 3 Days' in the #posted category). When I select 'Reading', the 5 London jobs should vanish from the main part of the page but the category_sidebar should still show me that I have the option of selecting London jobs as well. The job count next to 'London' should remain '5', indicating that I will see 5 additional jobs if I select this box.

The modification is to avoid this:
![Screenshot 2024-06-11 at 14 29 28](https://github.com/Ches-ctrl/Cheddar/assets/56164007/6515c0c0-1d57-4b19-9c04-76fde68d3a48)

And also meaningless counts appearing within a radio-button category, like this:
![Screenshot 2024-06-11 at 14 30 50](https://github.com/Ches-ctrl/Cheddar/assets/56164007/18746e5a-0198-4fc1-bbfe-5c54e964115c)

Added tests:

- category_sidebar_spec
- job_filter_spec

2024-06-11 17:45 UTC, patanj101 commented
Interesting ... I have been working on the same problematic last weekend on a page name "/opportunities" .
I am curious to have your opinion about my solution on the same issue.

https://github.com/Ches-ctrl/Cheddar/commit/edbc5ec31af802fa3c919eaebdd317de526d17bb

2024-06-12 12:09 UTC, Ches-ctrl commented on config/application.rb
Do we need this autoload path? Doesn't rails handle this automatically?

2024-06-12 12:49 UTC, patanj101 commented on config/application.rb
Nice catch. We don't need it. I have created similar folders for Queries & Tasks objects without needed it

2024-06-12 14:34 UTC, Ches-ctrl requested changes
Can you remove the autoload?

2024-06-14 10:18 UTC, daniel-sussman commented
Charlie, thanks for making those changes! I've sorted the FactoryBot problem, so this should be good to go.

2024-06-14 16:52 UTC, daniel-sussman commented
> Interesting ... I have been working on the same problematic last weekend on a page name "/opportunities" . I am curious to have your opinion about my solution on the same issue.
> 
> [edbc5ec](https://github.com/Ches-ctrl/Cheddar/commit/edbc5ec31af802fa3c919eaebdd317de526d17bb)

Thanks for sharing this, JB! I need to take some time to understand what you're doing with facets. However, I'm interested in this line:

```
  def facet_oppotunities(exemption)
    FacetOpportunitiesFetcher.call(Job.all, @params.except(exemption))
  end
```
It seems like this will make several database calls, since the method's called by every category. Is it possible to eager_load Job.all so that we only need to access the database once? I wonder what the best way to do this would be? I had this question when making my own edits to CategorySidebar but couldn't find an elegant solution.

2024-06-17 16:58 UTC, Ches-ctrl approved these changes
Approve

2024-06-17 16:58 UTC, merged