code clean up
Ches-ctrl/Cheddar pull request #63
Opened 2024-03-01 22:11 UTC by chrisgeek

Code Clean up
Search form works perfectly now
The search filter on the left side of the page needs to be looked at and fixed in another PR, the resource variable is no longer available. 
Need the reviewers to test the job refactoring and ensure it works as expected.

2024-03-01 23:00 UTC, daniel-sussman requested changes
Nice work, Chris. Let's discuss how best to refactor the sidebar logic.

2024-03-01 23:00 UTC, daniel-sussman commented on app/controllers/jobs_controller.rb
Great job on the search implementation. All of the if params[:resource].present? &c. stuff can be replaced by your lines 73-77. However, all code above line 33 is necessary for the sidebar logic. This file seems to revert that code to an earlier version, before I revised it in response to changes to the view files.

2024-03-01 23:00 UTC, daniel-sussman commented on app/models/job.rb
if geo = results.first does two things at once: 1) checks whether the geomapping API was able to associate the job's location string with any results, and 2) it sets geo to the first (i.e. most probable) geospatial result. Double equals sign is not intended.

2024-03-01 23:00 UTC, daniel-sussman commented on app/views/jobs/_filter_category_sidebar.html.erb
The changes to resources will break the sidebar. Please revert them for now.

2024-03-01 23:00 UTC, daniel-sussman commented on app/views/jobs/index.html.erb
Please don't comment out the filter sidebar!

2024-03-01 23:00 UTC, daniel-sussman commented on app/services/job_application/apply_job_service.rb
Ilya can confirm this, but pretty sure DefaultMale and DefaultFemale can be removed.

2024-03-04 09:44 UTC, closed without merging

2024-03-05 11:08 UTC, Ches-ctrl commented on app/services/job_application/apply_job_service.rb
Let's hold on removing these as I'd like there to be default values for users